#Development for the front end. This builds the static code

# Pull base image - we're running it on Ubuntu!
FROM node

RUN mkdir wldev
WORKDIR /wldev

# NPMINEM
COPY ./package.json /wldev/
COPY ./node_modules /wldev/node_modules
# RUN npm install COPYing them in to cut down on docker build time

COPY ./webpack.config.js /wldev/
COPY ./.babelrc /wldev/
COPY ./.eslintrc /wldev/
COPY ./.eslintignore /wldev/

# ADD the working files
RUN mkdir dist
RUN mkdir src

VOLUME ["/wldev/src", "/wldev/dist"]

# Expose ports.
EXPOSE 8080

# Define default command.
CMD ["npm", "run", "watch"] #in the docker-compose.dev.yml file this is overridden