#Development for the front end. We're using webpack's dev server so no need for nginx here

# Pull base image with nod ealready on it
FROM node

RUN mkdir wldev
WORKDIR /wldev

# ADD the config files
COPY ./package.json /wldev/
COPY ./webpack.config.js /wldev/
COPY ./.babelrc /wldev/

# Install!
RUN npm install

# ADD the working files
RUN mkdir dist
RUN mkdir src
# COPY ./dist/ /wldev/dist
# COPY ./src/ /wldev/src

# Expose ports.
EXPOSE 8080

# Define default command.
RUN echo "hello"
RUN ls
RUN dir
RUN pwd
CMD ["npm", "run", "start"]