#Development for the front end. This builds the static code

# Pull base image - we're running it on Ubuntu!
FROM node

RUN mkdir wldev
WORKDIR /wldev

# ADD the config files
COPY ./package.json /wldev/
COPY ./webpack.config.js /wldev/
COPY ./.babelrc /wldev/

# Install!
RUN npm install

# ADD the working files
RUN mkdir dist
RUN mkdir src

VOLUME ["/wldev/src", "/wldev/dist"]

# Expose ports.
EXPOSE 8080

# Define default command.
CMD ["npm", "run", "watch"] #in the docker-compose.dev.yml file this is overridden